---
- name: Extract private and public RSA keys and save them to id_rsa and id_rsa.pub respectively
  hosts: localhost
  gather_facts: no
  vars:
  vars_files:
  - secrets.yml

  tasks:

  - name: Extract keys
    ansible.builtin.shell: |
      echo "{{ ssh_key }}" > id_rsa
      echo "{{ ssh_pubkey }}" > id_rsa.pub
      chmod 400 id_rsa*
      exit 0

