---
- name: Extract private and public RSA keys and save them to id_rsa and id_rsa.pub respectively
  hosts: localhost
  gather_facts: no
  vars:
  vars_files:
  - secrets.yml

  tasks:

  - name: Extract private key
    ansible.builtin.shell: echo {{ ssh_key }} > id_rsa

  - name: Extract public key
    ansible.builtin.shell: echo {{ ssh_pubkey }} > id_rsa.pub

